#!/bin/bash
set -e

[ ! -d $HOME/Dropbox/Backups/stringer ] && exit
cd $HOME/Dropbox/Backups/stringer
[ -f latest.dump ] && rm latest.dump
ssh lana pg_dump -Fc -Ustringer stringer_live > latest.dump
[ -f 5.dump ] && rm 5.dump
[ -f 4.dump ] && mv 4.dump 5.dump
[ -f 3.dump ] && mv 3.dump 4.dump
[ -f 2.dump ] && mv 2.dump 3.dump
[ -f 1.dump ] && mv 1.dump 2.dump
[ -f latest.dump ] && mv latest.dump 1.dump
