#!/usr/bin/env bash
CURRENT_BRANCH=$(git symbolic-ref --short HEAD)
OTHER_REV=$(git rev-parse $1)
CURRENT_CREDS=$(rails credentials:show 2>/dev/null)
git checkout "$OTHER_REV" --quiet
OTHER_CREDS=$(rails credentials:show 2>/dev/null)
diff <(echo "$CURRENT_CREDS") <(echo "$OTHER_CREDS")
git checkout "$CURRENT_BRANCH" --quiet
