#!/usr/bin/env ruby

require 'fileutils'

IP_FILE = "#{ENV['HOME']}/Dropbox/ip-address"

File.file?(IP_FILE) or File.open(IP_FILE, 'w') { |f| '0.0.0.0' }

previous_ip = File.read(IP_FILE).chomp
current_ip = `/usr/bin/dig +short myip.opendns.com @resolver1.opendns.com`.chomp

if current_ip != previous_ip
  FileUtils.rm(IP_FILE)
  File.open(IP_FILE, 'w') { |f| f.puts(current_ip) }
end
