#!/usr/bin/env ruby

require 'fileutils'

IP_FILE = "#{ENV['HOME']}/.ip-address"

MAIL_TEMPLATE = <<~EOF
Subject: IP changed
%s
EOF

File.file?(IP_FILE) or File.open(IP_FILE, 'w') { |f| '0.0.0.0' }

previous_ip = File.read(IP_FILE).chomp
current_ip = `/usr/bin/dig +short myip.opendns.com @resolver1.opendns.com`.chomp

if current_ip != previous_ip
  FileUtils.rm(IP_FILE)
  File.open(IP_FILE, 'w') { |f| f.puts(current_ip) }
  `echo '#{MAIL_TEMPLATE % current_ip}' | msmtp -a camthompson cam@camthompson.com`
end
