#!/usr/bin/env ruby

require 'net/https'
require 'uri'
require 'cgi'

pinboard_url = "https://api.pinboard.in/v1/posts/add"
url_to_add = CGI.escape(ARGV[0])
description = CGI.escape(ARGV[1])
tags = CGI.escape(ARGV[2])
pinboard_url << "?url=#{url_to_add}&description=#{description}&tags=#{tags}"
uri = URI.parse(pinboard_url)

http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE

username = File.read(File.expand_path('~/.pinboard_account')).chomp
password = `security find-internet-password -wl Pinboard`.chomp

request = Net::HTTP::Get.new(uri.request_uri)
request.basic_auth(username, password)

http.request(request)
