#!/usr/bin/env ruby

require 'net/https'
require 'uri'
require 'yaml'

url_to_add = ARGV[0]
uri = URI.parse("https://www.instapaper.com/api/add?url=#{url_to_add}")

http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE

creds = YAML.load_file(File.expand_path('~/.instapaper_creds'))
username, password = creds['username'], creds['password']

request = Net::HTTP::Get.new(uri.request_uri)
request.basic_auth(username, password)

http.request(request)
