#!/usr/bin/env bash

set -e

if [[ ! "$OSTYPE" == darwin* ]]; then
  return
fi

batt=$(pmset -g batt | awk '/Internal/ { print $4,$3 }' |\
  sed 's/;//g' | sed 's/^charging/▲/' | sed 's/^discharging/▼/' |\
  sed -E 's/^(finishing charge|charged) //') |\
  sed -E 's/100% |//'
echo "$batt | "
