#!/usr/bin/env bash

set -e

if [[ ! "$OSTYPE" == darwin* ]]; then
  return
fi

batt=pmset -g batt | awk '/Internal/ { print $3,$2 }' |\
  sed 's/;//g' | sed 's/^charging/▲/' | sed 's/^discharging/▼/' |\
  sed -E 's/^(finishing charge|charged) //'
echo "$batt | "
