#!/bin/bash

set -e

if [[ ! "$OSTYPE" == darwin* ]]; then
  return
fi

echo '# Updating rubygems'
gem update --system
gem update

echo '# Updating Homebrew'
brew update
brew upgrade

echo '# Updating Vim and ZSH plugins'
cd "$HOME"/src/dotfiles
./update

echo '# Updating MacVim'
cd "$HOME"/src/vendor/macvim
git pull
make
rm -rf /Applications/MacVim.app/
mv "$HOME"/src/vendor/macvim/src/MacVim/build/release/MacVim.app /Applications/
