#!/bin/bash

set -e

if [[ ! "$OSTYPE" == darwin* ]]; then
  return
fi

echo '# Updating dotfiles and bin'
cd $HOME/bin; git pull; cd $HOME/src/dotfiles; git pull

echo '# Updating rubygems'
gem update --system
gem update
gem uninstall fileutils
echo '####################'

echo '# Updating Homebrew'
brew update
brew upgrade
brew upgrade --cask
brew reinstall parcel-beta
echo '####################'

echo '# Updating ZSH plugins'
cd "$HOME"/src/dotfiles
./update
