#!/bin/bash

set -e

if [[ ! "$OSTYPE" == darwin* ]]; then
  return
fi

echo '# Updating heroku'
heroku update
echo '####################'

echo '# Updating rubygems'
gem update --system
gem update
echo '####################'

echo '# Updating Homebrew'
brew update
brew upgrade
echo '####################'

echo '# Updating Vim and ZSH plugins'
cd "$HOME"/src/dotfiles
./update
echo '####################'

echo '# Updating MacVim'
cd "$HOME"/src/vendor/macvim
git pull
make distclean
./configure --with-features=huge --enable-luainterp --with-lua-prefix=/usr/local --enable-perlinterp --enable-pythoninterp --enable-python3interp --enable-rubyinterp --enable-cscope --with-macarchs=x86_64 --enable-gui=macvim
make
rm -rf /Applications/MacVim.app/
mv "$HOME"/src/vendor/macvim/src/MacVim/build/release/MacVim.app /Applications/

echo '# Updating neovim'
cd "$HOME"/src/vendor/neovim
rm -rf build/
git pull
make clean
make CMAKE_BUILD_TYPE=Release
make install

fix_open_with_duplicates

echo '# Updating repos on remote'
ssh lana 'cd $HOME/bin; git pull; cd $HOME/src/dotfiles; git pull'
ssh pair 'cd $HOME/bin; git pull; cd $HOME/src/dotfiles; git pull'
ssh pair 'gem update --system'
ssh pair 'gem update'
